#!/usr/bin/env python3
"""Measure the maximum header inclusion depth for each source file.

Uses compile_commands.json to extract individual compile commands and runs
them with ``-H -fsyntax-only``, bypassing the archiver/linker steps that
would fail when no ``.o`` files are produced.
"""

from __future__ import annotations

import csv
import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from build_optimiser.config import load_config, build_environment
from build_optimiser.metrics import parse_cmake_target_from_object_path


def parse_header_depth_stderr(stderr: str) -> dict[str, int]:
    """Parse GCC ``-H`` output from captured stderr.

    Lines look like: ``... path/to/header.h`` where dot count = depth.
    """
    max_depth = 0
    unique_headers: set[str] = set()
    total_includes = 0

    for line in stderr.splitlines():
        match = re.match(r"^(\.+)\s+(.+)$", line)
        if match:
            depth = len(match.group(1))
            header = match.group(2).strip()
            max_depth = max(max_depth, depth)
            unique_headers.add(header)
            total_includes += 1

    return {
        "max_depth": max_depth,
        "unique_headers": len(unique_headers),
        "total_includes": total_includes,
    }


def analyse_file(command_entry: dict, env: dict[str, str] | None = None) -> dict | None:
    """Run a single compile command with ``-H -fsyntax-only`` and parse the output."""
    source_file = command_entry.get("file", "")
    command = command_entry.get("command", "")
    directory = command_entry.get("directory", "")

    if not command:
        return None

    # Extract cmake target from -o flag
    output_match = re.search(r"-o\s+(\S+)", command)
    cmake_target = ""
    if output_match:
        cmake_target = parse_cmake_target_from_object_path(output_match.group(1)) or ""

    # Modify command: remove -o flag, add -H -fsyntax-only
    parts = command.split()
    new_parts = []
    skip_next = False
    for part in parts:
        if skip_next:
            skip_next = False
            continue
        if part == "-o":
            skip_next = True
            continue
        if part.startswith("-o"):
            continue
        new_parts.append(part)

    # Insert flags after the compiler
    if len(new_parts) > 1:
        new_parts.insert(1, "-H")
        new_parts.insert(2, "-fsyntax-only")

    try:
        result = subprocess.run(
            " ".join(new_parts),
            shell=True,
            cwd=directory,
            capture_output=True,
            text=True,
            timeout=120,
            env=env,
        )
        depth_info = parse_header_depth_stderr(result.stderr)
        return {
            "source_file": source_file,
            "cmake_target": cmake_target,
            **depth_info,
        }
    except (subprocess.TimeoutExpired, OSError) as e:
        print(f"Warning: Failed to analyse {source_file}: {e}", file=sys.stderr)
        return None


def main() -> None:
    cfg = load_config()
    build_dir = Path(cfg["build_dir"])
    raw_dir = Path(cfg["raw_data_dir"])
    raw_dir.mkdir(parents=True, exist_ok=True)
    ninja_jobs = cfg.get("ninja_jobs", 0)
    max_workers = ninja_jobs if ninja_jobs > 0 else None

    env = build_environment(cfg)

    # Read compile_commands.json (generated by an earlier collection step)
    cc_path = build_dir / "compile_commands.json"
    if not cc_path.exists():
        # Reconfigure to generate compile_commands.json
        from build_optimiser.config import build_cmake_command

        cmd = build_cmake_command(cfg)
        print(f"Configuring: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True, env=env)
        if result.returncode != 0:
            print(f"CMake configure failed:\n{result.stderr}", file=sys.stderr)
            sys.exit(1)

    with open(cc_path) as f:
        compile_commands = json.load(f)

    print(f"Processing {len(compile_commands)} files...")

    results = []
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(analyse_file, entry, env): entry
            for entry in compile_commands
        }
        for i, future in enumerate(as_completed(futures)):
            result = future.result()
            if result:
                results.append(result)
            if (i + 1) % 100 == 0:
                print(f"  Processed {i + 1}/{len(compile_commands)} files")

    output_path = raw_dir / "header_depth.csv"
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["source_file", "cmake_target", "max_depth", "unique_headers", "total_includes"],
        )
        writer.writeheader()
        for r in sorted(results, key=lambda x: x["source_file"]):
            writer.writerow(r)

    print(f"Wrote {len(results)} entries to {output_path}")


if __name__ == "__main__":
    main()
