#!/usr/bin/env python3
"""
generate_messages.py - Code generator for message classes from .def files.

Usage: python3 generate_messages.py <def_file> <output_dir>

Reads a messages.def file and produces 4 C++ source files:
  - messages.h
  - messages.cpp
  - message_registry.h
  - message_registry.cpp
"""

import os
import sys

# ---------------------------------------------------------------------------
# Type mapping from .def types to C++ types
# ---------------------------------------------------------------------------

TYPE_MAP = {
    "uint32": "uint32_t",
    "int64": "int64_t",
    "string": "std::string",
    "double": "double",
}


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------


def parse_def_file(path):
    """
    Parse a messages.def file and return a list of message descriptors.

    Each descriptor is a dict:
        { "name": str, "fields": [ {"type": str, "name": str}, ... ] }

    Rules:
      - Lines starting with '#' are comments and are ignored.
      - Blank lines are ignored.
      - A line matching 'message <Name> {' opens a new message block.
      - A line matching '<type> <field_name>;' (indented) adds a field.
      - A line containing only '}' closes the current message block.
    """
    messages = []
    current = None

    with open(path, "r") as fh:
        for raw_line in fh:
            line = raw_line.strip()

            # Skip blank lines and comments
            if not line or line.startswith("#"):
                continue

            # Opening a message block
            if line.startswith("message ") and line.endswith("{"):
                parts = line.split()
                # parts = ["message", "<Name>", "{"]
                name = parts[1]
                current = {"name": name, "fields": []}
                continue

            # Closing a message block
            if line == "}":
                if current is not None:
                    messages.append(current)
                    current = None
                continue

            # Field declaration inside a block
            if current is not None and line.endswith(";"):
                field_decl = line.rstrip(";").strip()
                parts = field_decl.split()
                if len(parts) == 2:
                    field_type, field_name = parts
                    current["fields"].append(
                        {
                            "type": field_type,
                            "name": field_name,
                        }
                    )

    return messages


def cpp_type(def_type):
    """Map a .def type string to its C++ equivalent."""
    return TYPE_MAP.get(def_type, def_type)


# ---------------------------------------------------------------------------
# Generator: messages.h
# ---------------------------------------------------------------------------


def gen_messages_h(messages):
    lines = []

    lines.append("#ifndef FIXTURE_GENERATED_MESSAGES_H")
    lines.append("#define FIXTURE_GENERATED_MESSAGES_H")
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// messages.h  --  AUTO-GENERATED FILE, DO NOT EDIT MANUALLY")
    lines.append("// Generated by generate_messages.py from messages.def")
    lines.append("// ============================================================")
    lines.append("")
    lines.append("// Project includes (needed for type aliases and error codes).")
    lines.append('#include "core/types.h"')
    lines.append("")
    lines.append("// Standard library includes (deliberately over-inclusive so that")
    lines.append("// all generated method bodies have what they need).")
    lines.append("#include <string>")
    lines.append("#include <cstdint>")
    lines.append("#include <vector>")
    lines.append("#include <memory>")
    lines.append("#include <functional>")
    lines.append("#include <stdexcept>")
    lines.append("#include <algorithm>")
    lines.append("#include <sstream>")
    lines.append("#include <iostream>")
    lines.append("")

    for msg in messages:
        lines.extend(_gen_struct(msg))
        lines.append("")

    lines.append("#endif // FIXTURE_GENERATED_MESSAGES_H")
    lines.append("")

    return "\n".join(lines)


def _gen_struct(msg):
    """Return a list of lines for one message struct definition."""
    name = msg["name"]
    fields = msg["fields"]
    lines = []

    # ----- Opening comment block -----
    lines.append("// " + "=" * 60)
    lines.append("// Message: " + name)
    lines.append("// " + "=" * 60)
    lines.append("")
    lines.append("struct " + name)
    lines.append("{")

    # ----- Field declarations -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Data members")
    lines.append("    // --------------------------------------------------------")
    lines.append("")
    for f in fields:
        lines.append("    " + cpp_type(f["type"]) + " " + f["name"] + ";")
    lines.append("")

    # ----- Default constructor -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Default constructor")
    lines.append("    // Initialises all members to their zero / empty values.")
    lines.append("    // --------------------------------------------------------")
    default_inits = []
    for f in fields:
        ct = cpp_type(f["type"])
        if ct in ("uint32_t", "int64_t", "double"):
            default_inits.append("        " + f["name"] + "(0)")
        else:
            default_inits.append("        " + f["name"] + "()")
    lines.append("    " + name + "()")
    if default_inits:
        lines.append("        : " + "\n        , ".join(i.strip() for i in default_inits))
    lines.append("    {}")
    lines.append("")

    # ----- Parameterised constructor -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Parameterised constructor")
    lines.append("    // --------------------------------------------------------")
    param_list = []
    for f in fields:
        ct = cpp_type(f["type"])
        if ct == "std::string":
            param_list.append("const std::string& " + f["name"] + "_")
        else:
            param_list.append(ct + " " + f["name"] + "_")
    param_str = ",\n        ".join(param_list)
    lines.append("    explicit " + name + "(")
    lines.append("        " + param_str + ")")
    inits = ["        " + f["name"] + "(" + f["name"] + "_)" for f in fields]
    lines.append("        : " + "\n        , ".join(i.strip() for i in inits))
    lines.append("    {}")
    lines.append("")

    # ----- Copy / move (defaulted) -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Copy and move operations (compiler-generated defaults)")
    lines.append("    // --------------------------------------------------------")
    lines.append("    " + name + "(const " + name + "& other) = default;")
    lines.append("    " + name + "& operator=(const " + name + "& other) = default;")
    lines.append("    " + name + "(" + name + "&& other) noexcept = default;")
    lines.append("    " + name + "& operator=(" + name + "&& other) noexcept = default;")
    lines.append("")

    # ----- operator== -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Equality comparison")
    lines.append("    // --------------------------------------------------------")
    lines.append("    bool operator==(const " + name + "& other) const")
    lines.append("    {")
    conds = ["        " + f["name"] + " == other." + f["name"] for f in fields]
    lines.append("        return " + "\n            && ".join(c.strip() for c in conds) + ";")
    lines.append("    }")
    lines.append("")

    # ----- operator!= -----
    lines.append("    bool operator!=(const " + name + "& other) const")
    lines.append("    {")
    lines.append("        return !(*this == other);")
    lines.append("    }")
    lines.append("")

    # ----- operator< -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Less-than comparison (allows use as std::map key)")
    lines.append("    // --------------------------------------------------------")
    lines.append("    bool operator<(const " + name + "& other) const")
    lines.append("    {")
    # Lexicographic on fields
    for i, f in enumerate(fields):
        lines.append("        if (" + f["name"] + " != other." + f["name"] + ")")
        lines.append("            return " + f["name"] + " < other." + f["name"] + ";")
    lines.append("        return false; // all fields equal")
    lines.append("    }")
    lines.append("")

    # ----- serialize (declaration) -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Serialisation / deserialisation")
    lines.append("    // Delimiter used between fields is '|'.")
    lines.append("    // --------------------------------------------------------")
    lines.append("    std::string serialize() const;")
    lines.append("")
    lines.append("    static " + name + " deserialize(const std::string& data);")
    lines.append("")

    # ----- type_name (inline) -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Static metadata")
    lines.append("    // --------------------------------------------------------")
    lines.append("    static std::string type_name()")
    lines.append("    {")
    lines.append('        return "' + name + '";')
    lines.append("    }")
    lines.append("")

    # ----- to_string (declaration) -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Human-readable representation")
    lines.append("    // --------------------------------------------------------")
    lines.append("    std::string to_string() const;")
    lines.append("")

    # ----- validate (declaration) -----
    lines.append("    // --------------------------------------------------------")
    lines.append("    // Validation")
    lines.append("    // Returns true when all fields pass basic sanity checks.")
    lines.append("    // --------------------------------------------------------")
    lines.append("    bool validate() const;")
    lines.append("")

    lines.append("};  // struct " + name)

    return lines


# ---------------------------------------------------------------------------
# Generator: messages.cpp
# ---------------------------------------------------------------------------


def gen_messages_cpp(messages):
    lines = []

    lines.append("// ============================================================")
    lines.append("// messages.cpp  --  AUTO-GENERATED FILE, DO NOT EDIT MANUALLY")
    lines.append("// Generated by generate_messages.py from messages.def")
    lines.append("// ============================================================")
    lines.append("")
    lines.append('#include "messages.h"')
    lines.append("")
    lines.append("#include <sstream>")
    lines.append("#include <stdexcept>")
    lines.append("")

    for msg in messages:
        lines.extend(_gen_impl(msg))
        lines.append("")

    return "\n".join(lines)


def _gen_impl(msg):
    name = msg["name"]
    fields = msg["fields"]
    lines = []
    delim = "|"

    lines.append("// " + "-" * 60)
    lines.append("// " + name + " implementation")
    lines.append("// " + "-" * 60)
    lines.append("")

    # ----- serialize -----
    lines.append("std::string " + name + "::serialize() const")
    lines.append("{")
    lines.append("    // Build a delimited string from all fields.")
    lines.append("    // Delimiter: '" + delim + "'")
    lines.append("    std::ostringstream oss;")
    for i, f in enumerate(fields):
        if i > 0:
            lines.append('    oss << "' + delim + '";')
        lines.append("    oss << " + f["name"] + ";")
    lines.append("    return oss.str();")
    lines.append("}")
    lines.append("")

    # ----- deserialize -----
    lines.append(name + " " + name + "::deserialize(const std::string& data)")
    lines.append("{")
    lines.append("    // Split the serialised string on the '" + delim + "' delimiter.")
    lines.append("    std::istringstream iss(data);")
    lines.append("    std::string token;")
    lines.append("    std::vector<std::string> tokens;")
    lines.append("")
    lines.append("    while (std::getline(iss, token, '" + delim + "'))")
    lines.append("    {")
    lines.append("        tokens.push_back(token);")
    lines.append("    }")
    lines.append("")
    lines.append("    if (tokens.size() < " + str(len(fields)) + ")")
    lines.append("    {")
    lines.append('        throw std::runtime_error("' + name + '::deserialize: insufficient fields in data");')
    lines.append("    }")
    lines.append("")
    lines.append("    " + name + " result;")
    for i, f in enumerate(fields):
        ct = cpp_type(f["type"])
        if ct == "std::string":
            lines.append("    result." + f["name"] + " = tokens[" + str(i) + "];")
        elif ct == "uint32_t":
            lines.append("    result." + f["name"] + " = static_cast<uint32_t>(std::stoul(tokens[" + str(i) + "]));")
        elif ct == "int64_t":
            lines.append("    result." + f["name"] + " = static_cast<int64_t>(std::stoll(tokens[" + str(i) + "]));")
        elif ct == "double":
            lines.append("    result." + f["name"] + " = std::stod(tokens[" + str(i) + "]);")
        else:
            lines.append("    result." + f["name"] + " = tokens[" + str(i) + "]; // unknown type")
    lines.append("    return result;")
    lines.append("}")
    lines.append("")

    # ----- to_string -----
    lines.append("std::string " + name + "::to_string() const")
    lines.append("{")
    lines.append("    std::ostringstream oss;")
    lines.append('    oss << "' + name + '{";')
    for i, f in enumerate(fields):
        sep = ", " if i < len(fields) - 1 else ""
        lines.append('    oss << "' + f["name"] + '=" << ' + f["name"] + ' << "' + sep + '";')
    lines.append('    oss << "}";')
    lines.append("    return oss.str();")
    lines.append("}")
    lines.append("")

    # ----- validate -----
    lines.append("bool " + name + "::validate() const")
    lines.append("{")
    lines.append("    // Basic sanity: string fields must be non-empty;")
    lines.append("    // numeric id / version fields must be > 0 where applicable.")
    for f in fields:
        ct = cpp_type(f["type"])
        if ct == "std::string":
            lines.append("    if (" + f["name"] + ".empty()) { return false; }")
        elif ct in ("uint32_t",) and f["name"] in ("id", "version", "source_id", "status_code", "count"):
            lines.append("    if (" + f["name"] + " == 0) { return false; }")
    lines.append("    return true;")
    lines.append("}")

    return lines


# ---------------------------------------------------------------------------
# Generator: message_registry.h
# ---------------------------------------------------------------------------


def gen_message_registry_h(messages):
    lines = []

    lines.append("#ifndef FIXTURE_GENERATED_MESSAGE_REGISTRY_H")
    lines.append("#define FIXTURE_GENERATED_MESSAGE_REGISTRY_H")
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// message_registry.h  --  AUTO-GENERATED FILE, DO NOT EDIT MANUALLY")
    lines.append("// Generated by generate_messages.py from messages.def")
    lines.append("// ============================================================")
    lines.append("")
    lines.append('#include "messages.h"')
    lines.append("")
    lines.append("#include <map>")
    lines.append("#include <typeindex>")
    lines.append("#include <functional>")
    lines.append("#include <vector>")
    lines.append("#include <string>")
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// MessageRegistry")
    lines.append("//")
    lines.append("// A singleton registry that maps message type names to factory")
    lines.append("// functions.  Each factory produces a default-serialised")
    lines.append("// instance of the corresponding message type.")
    lines.append("// ============================================================")
    lines.append("")
    lines.append("class MessageRegistry")
    lines.append("{")
    lines.append("public:")
    lines.append("")
    lines.append("    // Factory function type: produces a serialised default instance.")
    lines.append("    using FactoryFn = std::function<std::string()>;")
    lines.append("")
    lines.append("    // ----------------------------------------------------------")
    lines.append("    // Singleton access")
    lines.append("    // ----------------------------------------------------------")
    lines.append("    static MessageRegistry& instance();")
    lines.append("")
    lines.append("    // ----------------------------------------------------------")
    lines.append("    // Registration")
    lines.append("    // ----------------------------------------------------------")
    lines.append("    void register_type(const std::string& name, FactoryFn factory);")
    lines.append("")
    lines.append("    // ----------------------------------------------------------")
    lines.append("    // Queries")
    lines.append("    // ----------------------------------------------------------")
    lines.append("    bool has_type(const std::string& name) const;")
    lines.append("")
    lines.append("    std::vector<std::string> registered_types() const;")
    lines.append("")
    lines.append("private:")
    lines.append("")
    lines.append("    // Private constructor — use instance() instead.")
    lines.append("    MessageRegistry() = default;")
    lines.append("")
    lines.append("    // The map from type name -> factory function.")
    lines.append("    std::map<std::string, FactoryFn> factories_;")
    lines.append("")
    lines.append("};  // class MessageRegistry")
    lines.append("")
    lines.append("#endif // FIXTURE_GENERATED_MESSAGE_REGISTRY_H")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Generator: message_registry.cpp
# ---------------------------------------------------------------------------


def gen_message_registry_cpp(messages):
    lines = []

    lines.append("// ============================================================")
    lines.append("// message_registry.cpp  --  AUTO-GENERATED FILE, DO NOT EDIT MANUALLY")
    lines.append("// Generated by generate_messages.py from messages.def")
    lines.append("// ============================================================")
    lines.append("")
    lines.append('#include "message_registry.h"')
    lines.append("")

    # ----- instance() -----
    lines.append("// ------------------------------------------------------------------")
    lines.append("// MessageRegistry::instance()")
    lines.append("// Returns the process-wide singleton.")
    lines.append("// ------------------------------------------------------------------")
    lines.append("MessageRegistry& MessageRegistry::instance()")
    lines.append("{")
    lines.append("    static MessageRegistry registry;")
    lines.append("    return registry;")
    lines.append("}")
    lines.append("")

    # ----- register_type() -----
    lines.append("// ------------------------------------------------------------------")
    lines.append("// MessageRegistry::register_type()")
    lines.append("// Associates a type name with a factory function.")
    lines.append("// ------------------------------------------------------------------")
    lines.append("void MessageRegistry::register_type(const std::string& name, FactoryFn factory)")
    lines.append("{")
    lines.append("    factories_[name] = factory;")
    lines.append("}")
    lines.append("")

    # ----- has_type() -----
    lines.append("// ------------------------------------------------------------------")
    lines.append("// MessageRegistry::has_type()")
    lines.append("// Returns true if the given type name has been registered.")
    lines.append("// ------------------------------------------------------------------")
    lines.append("bool MessageRegistry::has_type(const std::string& name) const")
    lines.append("{")
    lines.append("    return factories_.find(name) != factories_.end();")
    lines.append("}")
    lines.append("")

    # ----- registered_types() -----
    lines.append("// ------------------------------------------------------------------")
    lines.append("// MessageRegistry::registered_types()")
    lines.append("// Returns the names of all registered types in sorted order.")
    lines.append("// ------------------------------------------------------------------")
    lines.append("std::vector<std::string> MessageRegistry::registered_types() const")
    lines.append("{")
    lines.append("    std::vector<std::string> names;")
    lines.append("    names.reserve(factories_.size());")
    lines.append("    for (const auto& kv : factories_)")
    lines.append("    {")
    lines.append("        names.push_back(kv.first);")
    lines.append("    }")
    lines.append("    return names;")
    lines.append("}")
    lines.append("")

    # ----- RegistryInitializer -----
    lines.append("// ------------------------------------------------------------------")
    lines.append("// RegistryInitializer")
    lines.append("//")
    lines.append("// A namespace-scope struct whose constructor registers all known")
    lines.append("// message types.  The static instance below ensures this runs")
    lines.append("// before main().")
    lines.append("// ------------------------------------------------------------------")
    lines.append("namespace")
    lines.append("{")
    lines.append("")
    lines.append("struct RegistryInitializer")
    lines.append("{")
    lines.append("    RegistryInitializer()")
    lines.append("    {")
    lines.append("        MessageRegistry& reg = MessageRegistry::instance();")
    lines.append("")
    for msg in messages:
        n = msg["name"]
        lines.append("        // Register " + n)
        lines.append("        reg.register_type(")
        lines.append('            "' + n + '",')
        lines.append("            []() -> std::string")
        lines.append("            {")
        lines.append("                return " + n + "().serialize();")
        lines.append("            });")
        lines.append("")
    lines.append("    }  // RegistryInitializer()")
    lines.append("};  // struct RegistryInitializer")
    lines.append("")
    lines.append("// Trigger registration at program startup.")
    lines.append("static RegistryInitializer init;")
    lines.append("")
    lines.append("}  // anonymous namespace")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    if len(sys.argv) != 3:
        print("Usage: python3 generate_messages.py <def_file> <output_dir>", file=sys.stderr)
        sys.exit(1)

    def_file = sys.argv[1]
    output_dir = sys.argv[2]

    if not os.path.isfile(def_file):
        print("Error: def file not found: " + def_file, file=sys.stderr)
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    print("Parsing: " + def_file)
    messages = parse_def_file(def_file)
    print("Found " + str(len(messages)) + " message(s): " + ", ".join(m["name"] for m in messages))

    files = {
        "messages.h": gen_messages_h(messages),
        "messages.cpp": gen_messages_cpp(messages),
        "message_registry.h": gen_message_registry_h(messages),
        "message_registry.cpp": gen_message_registry_cpp(messages),
    }

    for filename, content in files.items():
        out_path = os.path.join(output_dir, filename)
        with open(out_path, "w") as fh:
            fh.write(content)
        line_count = content.count("\n")
        print("Wrote: " + out_path + "  (" + str(line_count) + " lines)")

    print("Done.")


if __name__ == "__main__":
    main()
